import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex justify-center items-start bg-gray-300 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full max-w-[412px] min-h-screen bg-white mx-auto flex flex-col">
          {children}
        </div>
      </body>
    </html>
  );
}
